name = "swrp"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "swrp_lore"
database_id = "445da21d-ecea-452e-8c43-6c355547695b"

[vars]
ROBLOX_CLIENT_ID = "4826975489404838124"

[[d1_databases]]
binding = "RECOMMENDED"
database_name = "swrp-recommended"
database_id = "9d031406-b17b-4d8a-9264-85f68f40f2a5"
